try:
    num = int(input("Enter your number : "))
    print(num)
except ValueError as ex :
    print("execption , ex")



print("I am outside the trying block")